name: Compile s&box game

on: push

env:
  UPDATE_SCRIPT: "C:\\scripts\\update-sbox.bat"
  ENGINE_PATH: "C:\\apps\\sbox"

jobs:
  compile:
    runs-on: [self-hosted, windows]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Update engine
        run: $UPDATE_SCRIPT

      - name: Pull sbox-automator
        run: |
          git clone https://github.com/gio3k/sbox-automator
        shell: cmd

      - name: Build sbox-automator
        run: |
          dotnet build sbox-automator\sbox-automator\sbox-automator.csproj
        shell: cmd

      - name: Run sbox-automator
        run: >
          sbox-automator\sbox-automator\bin\Debug\net9.0\sbox-automator.exe 
          --engine $ENGINE_PATH
          --project .
          --script sbox-automator\NothingPlugin.cs
        shell: cmd
