name: Create Bug 🐞
description: Prepare a bug for triage
title: "🐞 "
labels: ["bug"]
projects: ["Small-Fish-Dev/10"]
body:
  - type: markdown
    attributes:
      value: |
        Report a bug. It'll be added to the [project](https://github.com/orgs/Small-Fish-Dev/projects/10) for triage.
  - type: textarea
    id: bug-what-happens
    attributes:
      label: What's the bug?
      placeholder: What does the bug cause?
    validations:
      required: true
  - type: textarea
    id: bug-fix-ideas
    attributes:
      label: Any ideas about possible fixes?
      placeholder: Don't worry, this is optional. If you can't think of anything now and you learn something later, feel free to comment.
